POST http://localhost:3000/api/authenticate
Content-Type: application/json

{
	"username": "admin",
	"password": "test"
}

###

POST https://authorization-server-woad.vercel.app/api/authenticate

{
	"username": "admin",
	"password": "test"
}



