POST http://localhost:3000/api/authenticate
Content-Type: application/json

{
	"username": "admin",
	"password": "test"
}

###

POST https://authorization-server-saeid-fastmailfm.vercel.app/api/authenticate
Content-Type: application/json

{
	"username": "admin",
	"password": "test"
}

###

GET http://localhost:3000/api/getTokens
Content-Type: application/json




